### ISSUE TITLE
criação de página sobre

### ISSUE THREAD

**Issue by soraiajacome** [jacomesoraia/github-master#3]
vcs poderiam criar uma página sobre? agradeço.

**Comment by jacomesoraia** [comment]
pagina está em criação

**Comment by soraiajacome** [comment]
obg estou aguardando
________________________________
De: soraia jacome ***@***.***>
Enviado: domingo, 18 de junho de 2023 20:48
Para: jacomesoraia/github-master ***@***.***>
Cc: segundo perfil ***@***.***>; Author ***@***.***>
Assunto: Re: [jacomesoraia/github-master] criação de página sobre (Issue #3)


pagina está em criação
